"""格基 AKA 论文复现项目的共享基础设施。"""

from lattice_aka_repro.c2lake_core import (
    C2LakeCoreError,
    C2LakeHashSuite,
    C2LakeKeyPair,
    C2LakeMasterSecret,
    C2LakePartialPrivateKey,
    C2LakePrivateKey,
    C2LakeProfile,
    C2LakePublicKey,
    C2LakePublicParameters,
    C2LakeUserSecret,
    bounded_ternary_vector,
    centered_norm,
    centered_representative,
    dot_mod,
    encode_zq_array,
    extract_partial_private_key,
    load_c2lake_profile,
    matrix_times_vector,
    set_secret_value,
    setup,
    uniform_mod_q,
    vector_times_matrix,
    verify_and_assemble_key,
    verify_partial_key,
    zq_add,
    zq_scalar_mul,
)
from lattice_aka_repro.evidence import (
    RunMetadata,
    collect_run_metadata,
    ensure_artifact_dirs,
    write_metadata_json,
)
from lattice_aka_repro.profiles import load_profile
from lattice_aka_repro.randomness import seeded_rng
from lattice_aka_repro.spec_validation import (
    SpecValidationResult,
    ValidationCheck,
    ValidationIssue,
    render_report,
    validate_specs,
    write_validation_outputs,
)

__all__ = [
    "C2LakeCoreError",
    "C2LakeHashSuite",
    "C2LakeKeyPair",
    "C2LakeMasterSecret",
    "C2LakePartialPrivateKey",
    "C2LakePrivateKey",
    "C2LakeProfile",
    "C2LakePublicKey",
    "C2LakePublicParameters",
    "C2LakeUserSecret",
    "RunMetadata",
    "SpecValidationResult",
    "ValidationCheck",
    "ValidationIssue",
    "bounded_ternary_vector",
    "centered_norm",
    "centered_representative",
    "collect_run_metadata",
    "dot_mod",
    "encode_zq_array",
    "ensure_artifact_dirs",
    "extract_partial_private_key",
    "load_c2lake_profile",
    "load_profile",
    "matrix_times_vector",
    "render_report",
    "seeded_rng",
    "set_secret_value",
    "setup",
    "uniform_mod_q",
    "validate_specs",
    "vector_times_matrix",
    "verify_and_assemble_key",
    "verify_partial_key",
    "write_metadata_json",
    "write_validation_outputs",
    "zq_add",
    "zq_scalar_mul",
]
